spring.application.name=enset-bot

# API Keys (NE PAS mettre les vraies valeurs ici)
spring.ai.openai.api-key=${OPENAI_API_KEY}
telegram.api.key=${TELEGRAM_BOT_TOKEN}

spring.ai.openai.chat.options.model=gpt-4o
server.port=8087
spring.ai.mcp.client.streamable-http.connections.mcprh.url=http://localhost:8989/mcp